<a href="https://colab.research.google.com/github/Akulverma2/AIML-projects/blob/main/03_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
iris = load_iris()
# Create DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
# Features (X) = all 4 columns
X = df
# Target (y) = flower category (0,1,2)
y = iris.target
print("Features (X):")
print(X.head())

print("\nTarget (y - Flower Class):")
print(y[:5])

Features (X):
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Target (y - Flower Class):
[0 0 0 0 0]


In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"\nTraining shape: {X_train.shape}")
print(f"Testing shape: {X_test.shape}")


Training shape: (120, 4)
Testing shape: (30, 4)


In [4]:
# Logistic Regression Model
log_model = LogisticRegression(max_iter=200)
log_model.fit(X_train, y_train)

print("\nLogistic Regression model training completed.")


Logistic Regression model training completed.


In [5]:
y_pred = log_model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\n------ Logistic Regression Results ------")
print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))


------ Logistic Regression Results ------
Accuracy: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [6]:
# Test on New Flower Data
new_data = [[5.1, 3.5, 1.4, 0.2]]  # must give 4 features now

new_flower_df = pd.DataFrame(new_data, columns=iris.feature_names)

predicted_class = log_model.predict(new_flower_df)[0]

print("\n------ New Flower Prediction ------")
print("Predicted Class:", predicted_class)
print("Predicted Flower Name:", iris.target_names[predicted_class])


------ New Flower Prediction ------
Predicted Class: 0
Predicted Flower Name: setosa
